import { ArrowRight, Bot, MessageSquare, Sparkles } from "lucide-react";
import Link from "next/link";
import type { DashboardSnapshot } from "@/lib/demo-data";
import { aiQuestions } from "@/lib/landing-content";
import { Button } from "@/components/ui/button";
import { SectionHeading } from "@/components/common/section-heading";

export function AIAssistantSection({ summary }: { summary: DashboardSnapshot }) {
  return <section id="ai-assistant" className="scroll-mt-24 px-5 py-24 sm:px-8 xl:px-12"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><SectionHeading eyebrow="AI city assistant" title="ถามข้อมูลเมืองได้ด้วยภาษาธรรมชาติ" description="ผู้ใช้งานสามารถสอบถามข้อมูลที่แสดงอยู่ใน Dashboard ได้โดยตรง เช่น สถานะกล้อง CCTV อุปกรณ์ Offline ค่าคุณภาพอากาศ เหตุการณ์ล่าสุด พื้นที่เสี่ยง หรือแนวโน้มข้อมูลย้อนหลัง" /><div className="mt-8 flex flex-wrap gap-2">{aiQuestions.map((question) => <span key={question} className="rounded-full border border-white/10 bg-white/[.03] px-3 py-2 text-xs text-[var(--text-secondary)]">“{question}”</span>)}</div><Button asChild variant="outline" className="mt-8"><Link href="/dashboard#ai-assistant">เปิด AI Assistant <ArrowRight className="size-4" /></Link></Button></div><div className="relative overflow-hidden rounded-[2rem] border border-violet-300/20 bg-[linear-gradient(145deg,rgba(63,48,108,.38),rgba(18,24,39,.8))] p-4 shadow-[0_24px_80px_rgba(76,29,149,.16)] sm:p-6"><div className="absolute -right-20 -top-20 size-56 rounded-full bg-violet-400/15 blur-3xl" /><div className="relative"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-violet-300/15 text-violet-200"><Bot className="size-5" /></span><div><p className="text-sm font-semibold text-white">City Intelligence Copilot</p><p className="text-[10px] text-violet-200/70">Context-aware · Permission-aware</p></div></div><span className="flex items-center gap-1.5 text-[10px] text-emerald-200"><span className="size-1.5 rounded-full bg-emerald-300" />Ready</span></div><div className="space-y-3 py-5"><div className="ml-auto max-w-[85%] rounded-2xl rounded-br-md bg-violet-300/15 px-4 py-3 text-sm leading-6 text-violet-50">สรุปภาพรวมสถานการณ์ของจังหวัดสิงห์บุรี</div><div className="flex max-w-[92%] gap-3 rounded-2xl rounded-bl-md border border-white/[.08] bg-black/15 px-4 py-3 text-sm leading-6 text-[var(--text-secondary)]"><Sparkles className="mt-1 size-4 shrink-0 text-violet-200" /><span>ขณะนี้มีเหตุการณ์เปิด <strong className="text-white">{summary.incidents.open}</strong> รายการ และแจ้งเตือนสำคัญ <strong className="text-[var(--nt-yellow)]">{summary.alerts.critical + summary.alerts.high + summary.alerts.warning}</strong> รายการ ระบบ CCTV ออนไลน์ <strong className="text-emerald-200">{summary.cctv.online}</strong> จุด</span></div></div><div className="flex items-center gap-2 rounded-xl border border-white/10 bg-black/15 px-3 py-2.5 text-xs text-[var(--text-muted)]"><MessageSquare className="size-4" />ถามต่อเกี่ยวกับข้อมูลเมืองได้ที่ Dashboard <ArrowRight className="ml-auto size-3.5" /></div></div></div></div></section>;
}
